/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./components/VueComponent3 copy.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Genres: typeof import('./components/Genres.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Index: typeof import('./components/Index.vue')['default']
    MenuGroup: typeof import('./components/MenuGroup.vue')['default']
    PreferencesView: typeof import('./components/PreferencesView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shops: typeof import('./components/Shops.vue')['default']
    ShopsNearBy: typeof import('./components/ShopsNearBy.vue')['default']
    SideDrawer: typeof import('./components/SideDrawer.vue')['default']
    VueComponent1: typeof import('./components/VueComponent1.vue')['default']
    VueComponent2: typeof import('./components/VueComponent2.vue')['default']
    VueComponent3: typeof import('./components/VueComponent3.vue')['default']
    VueComponent4: typeof import('./components/VueComponent4.vue')['default']
  }
}
